### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jgmuchiri** [MastaBaba/LoremFlickr#1]
Thanks for sharing!.
After editing the variables in initialize.php. I am getting an empty image

**Comment by MastaBaba** [comment]
Sorry to hear. I Just did a fresh install on a different server and it works fine for me:

```
http://00qq.com/lf/g/320/240/paris,girl/all 
```

(For future visitors: this won't be online forever.)

However, I did add some detail to the readme document, which you might want to check out.

Your server is likely throwing an error, which you can't see because image.php has its header set to

```
header("Content-Type: image/jpg");
```

If you comment out this line (line 129), you might see what error is thrown, allowing you to correct the issue.
